### ISSUE TITLE
Build Fails: firebase_auth Requires minSdkVersion 23 or Higher

### ISSUE THREAD

**Issue by sendhyrama** [yazdanhaider/Food-Delivery#1]
The project currently uses a minSdkVersion lower than 23, causing a build failure due to the latest version of the firebase_auth plugin requiring a minimum SDK version of 23. Updating the SDK version is necessary to resolve this compatibility issue and allow successful builds.

### Steps to Reproduce:
1. Clone the repository.
2. Open the project in Android Studio.
3. Ensure the minSdkVersion is set to a value lower than 23 (for example, 21).
4. Attempt to build the project.
5. The build fails with an error indicating that firebase_auth requires a minSdkVersion of 23 or higher.

### Expected Behavior:
The app should build successfully with the correct SDK version to maintain compatibility with Firebase plugins like firebase_auth.

### Observed Behavior:
The build fails with the following error message:
`The plugin firebase_auth requires a higher Android SDK version.
Fix this issue by adding the following to the file android/app/build.gradle:
android {
   defaultConfig {
     minSdkVersion 23
   }
}
`

### Proposed Solution:
Update the android/app/build.gradle file to change the minSdkVersion to 23:
`defaultConfig {
   minSdkVersion 23
}
`

### Expected Result:
After updating the minSdkVersion to 23, the project should build successfully without any issues related to Firebase plugins.

**Comment by yazdanhaider** [comment]
Great. Move on
