### ISSUE TITLE
Issue: Bottom Overflow Error on iOS During Order Receipt Generation After Checkout

### ISSUE THREAD

**Issue by yazdanhaider** [yazdanhaider/Food-Delivery#4]
## Description

I am encountering an issue on iOS devices during the order receipt generation after a successful checkout. Specifically, when adding 3 or more items to the cart and proceeding with the checkout, the following error is thrown in the order receipt generation step:
This issue only occurs on iOS devices and happens when the order receipt is being generated and displayed post-checkout. The receipt display seems to overflow, pushing the content outside of the visible area, and the pixel overflow error appears at the bottom of the screen.

## Steps to Reproduce

1. Run the app on an iOS device.
2. Add 3 or more items to the cart.
3. Proceed with the checkout process.
4. Observe the error in the order receipt display after the successful checkout.

## Expected Behavior

The order receipt should be displayed properly within the screen bounds without causing a pixel overflow.

## Actual Behavior

The order receipt display overflows the bottom of the screen, throwing a "Bottom overflowed by 300 pixels" error, making the content unreadable.

## Environment

- Device: iPhone (iOS 15.x)
- Flutter version: 3.x.x
- Firebase dependencies: `firebase_auth` version x.x.x, `cloud_firestore` version x.x.x
- UI Framework: Flutter (Custom UI for the receipt generation screen)

## Additional Information

- The issue does not appear when fewer than 3 items are added to the cart.
- This problem occurs only on iOS; Android does not seem to trigger the same error.
- The order receipt uses a ListView or a Column to display the list of ordered items.

Any guidance or suggestions to fix this overflow issue on iOS devices would be greatly appreciated!

![Simulator Screenshot - iPhone 15 Pro - 2024-10-11 at 00 57 59](https://github.com/user-attachments/assets/beaa0fcd-9a07-4b2f-97eb-b7c791816c11)

**Comment by SyedMuzamilShah** [comment]
Could you please assign this issue to me? I'm ready to start working on it.

**Comment by yazdanhaider** [comment]
> Could you please assign this issue to me? I'm ready to start working on it.

Great! Move forward, @SyedMuzamilShah and please make sure to thoroughly review the markdown file.

**Comment by SyedMuzamilShah** [comment]
The issue has been resolved. Please review the changes and let me know if any adjustments are needed. Thank you!

**Comment by yazdanhaider** [comment]
> The issue has been resolved. Please review the changes and let me know if any adjustments are needed. Thank you!

Thank you for contributing!! @SyedMuzamilShah 🚀
